# https://docs.docker.com/reference/compose-file/
services:
  # database for persistant data storage
  postgres:
    # https://hub.docker.com/_/postgres
    image: postgres:17
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Expose PostgreSQL to localhost ("local:container")
    volumes:
      - pg_data:/var/lib/postgresql/data # default PGDATA location: /var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d # init run all scripts by default in: /docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

  # kafka message queue with zookeeper config management
  zookeeper:
    # https://hub.docker.com/r/confluentinc/cp-zookeeper
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # monitor whether zookeeper is ready
    healthcheck:
      test: ["CMD", "sh", "-c", "echo > /dev/tcp/zookeeper/2181"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 1s
    networks:
      - microservices-net

  kafka:
    # https://hub.docker.com/r/confluentinc/cp-kafka
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
        # if zookeeper restarts, kafka will also restart
        restart: true
    ports:
      - "9092:9092" # For internal Docker use
      - "9093:9093" # For external access
    # monitor whether kafka is ready
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "echo > /dev/tcp/kafka/9092 && echo > /dev/tcp/kafka/9093",
        ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - microservices-net

  kafka-topic-creator:
    image: confluentinc/cp-kafka:7.7.1
    depends_on:
      kafka:
        condition: service_healthy
        # if kafka restart, this creator will not restart (only create once)
        restart: false
    entrypoint: >
      bash -c "
      /bin/kafka-topics --create --topic log-channel --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1;
      "
    networks:
      - microservices-net

  ##### YOUR SERVICES GO BELOW THIS LINE #####
  db-service:
    build:
      context: .
      dockerfile: src/db_service/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-net
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - PYTHONUNBUFFERED=1 

  logging-service:
    build:
      context: .
      dockerfile: src/logging_service/Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - microservices-net
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PYTHONUNBUFFERED=1 # See the log information for debugging
  
  api-service:
    build:
      context: .
      dockerfile: src/api_service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db-service
      - logging-service
    networks:
      - microservices-net
    environment:
      - DB_SERVICE_ADDR=db-service:50051
      - LOGGING_SERVICE_ADDR=logging-service:50052
      - PYTHONUNBUFFERED=1 

networks:
  microservices-net:
    driver: bridge

volumes:
  pg_data: # A placeholder volume without any configuration
